#!/usr/bin/env python3
"""caption.py — write the figure caption from the gold tables.

Written 2026-10-09, after the caption was hand-patched a dozen times across one session and
drifted: it claimed 390 country-centroid samples in one paragraph and 301 in another, and
318 localities where the table said 3,559. Every number in a caption is a claim about the
data, and a claim nobody can recompute is one nobody can check.

Nothing here is prose-with-numbers-typed-in. The narrative is a template; every figure in it
is read from data/gold/ at write time.

    python 01a_Literature/report/figures/caption.py
"""

from __future__ import annotations

import collections, csv, sys
from pathlib import Path

_HERE = Path(__file__).resolve()
sys.path[:0] = [str(_HERE.parents[2]), str(_HERE.parents[3])]
from _layout import GOLD, SEEDS

OUT = _HERE.parent / "map_crop_origins_caption.txt"


def tsv(p):
    with Path(p).open() as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


def main() -> None:
    tot = {r["crop"]: r for r in tsv(GOLD / "crop_totals.tsv")}
    keep = [k for k in ("Wheat", "Maize", "Rice", "Sorghum", "Barley", "Other cereal")
            if k in tot and tot[k]["included"] == "yes"]
    drop = [k for k in tot if tot[k]["included"] == "no"]
    rows = [r for r in tsv(GOLD / "crop_map.tsv") if r["crop"] in keep]
    geo = [r for r in rows if r["precision"] != "country"]
    ctr = [r for r in rows if r["precision"] == "country"]
    locs = tsv(GOLD / "cereal_localities.tsv")
    pr = collections.Counter(r["precision"] for r in geo)
    corrected = sum(v for k, v in pr.items() if k.startswith("corrected"))
    yrs = tsv(GOLD / "crop_year.tsv")
    hosts = tsv(GOLD / "cohort_hosts.tsv")
    fixes = tsv(SEEDS / "missing_localities.tsv") if (SEEDS / "missing_localities.tsv").exists() else []

    n_total = sum(int(tot[k]["runs"]) for k in keep)
    n_geo, n_ctr = sum(int(r["n"]) for r in geo), sum(int(r["n"]) for r in ctr)
    n_unplaced = sum(int(tot[k]["runs_unplaced"]) for k in keep)
    n_dated = sum(int(r["n"]) for r in yrs)
    years = sorted({int(r["year"]) for r in yrs})
    projects = len({r["BioProject"] for r in hosts
                    if any(r["host"].startswith(p) for p in
                           ("Triticum", "Zea mays", "Oryza sativa", "Sorghum bicolor"))})
    still = sum(1 for r in locs if r["precision"] == "country")
    applied = sum(1 for f in fixes if f.get("corrected", "").strip())

    tbl = "\n".join(
        f"  {k:<14}{int(tot[k]['runs']):>7,}{int(tot[k]['projects']):>11}"
        f"{int(tot[k]['localities']):>13}{int(tot[k]['runs_country_only']):>15}" for k in keep)
    dropped = ", ".join(f"{k.lower()} ({tot[k]['runs']})" for k in drop)

    txt = f"""Distribution of Field Cereal RNA-seq Studies
Caption for report/figures/panels/{{a_map, b_samples, c_localities,
d_year}}.{{png,pdf}}

GENERATED by report/figures/caption.py — do not hand-edit, the numbers will drift.

The four panels are rendered as separate files and are not assembled here. The
letters a-d below are the order they are meant to be read in, not a layout.


FULL CAPTION

Geographic, compositional and temporal distribution of the field cereal RNA-seq
cohort: {n_total:,} publicly archived samples from {projects} BioProjects, each curated to a
field setting against a quoted sentence in an available manuscript. Colour marks
the crop throughout.

(a) Map. One point per locality and crop. Point area is proportional to the
LOGARITHM of the number of samples there, so a larger point means more samples
but area is not proportional to count. Points are semi-transparent, so
overlapping localities compound into darker patches. Country outlines are drawn
in the background colour.

  Circles, marked "Locality" in the Resolution key ({n_geo:,} samples at
  {len({r['location'] for r in geo})} localities), sit at coordinates geocoded from the locality string
  recorded for the sample.

  Diamonds, marked "Country" ({n_ctr} samples across {len({r['location'] for r in ctr})} countries), sit at the
  centroid of the largest landmass polygon of their country. These samples name
  a country and nothing finer, so the diamond states WHICH COUNTRY and is drawn
  at a place nobody sampled. It is not a collection site and should not be read
  as one.

(b) Samples per crop and (c) distinct localities per crop. The same cohort
counted two ways. Axis values are scaled by the factor given in the axis title,
so a label of 3 in (b) is 3,000 samples and a label of 3 in (c) is 300
localities. Localities are distinct locality strings finer than a country, so
the bare-country samples add to (b) and not to (c), and repeated sampling of one
site across seasons counts once. (c) therefore counts localities the studies
NAMED, which is slightly more than the map can draw: {still} of those names resolve
no better than their own country and appear in (a) as diamonds.

(d) Year. Samples per year of collection, stacked by crop, over {years[0]} to {years[-1]}.
Only the first and last year are labelled, to give the range; every year in
between has its own bar. Based on the {n_dated:,} of {n_total:,} samples carrying a
collection date. Bars rather than a continuous series, because year here is a
discrete count: an area or line would draw a slope between {years[3]} and {years[4]}
asserting collection at every instant in between, and none occurred. Every year
in the range has a position on the axis, so a year with no collection reads as
an absent bar rather than being skipped.

                samples   projects   localities   country-only
{tbl}

The crops are not comparable in shape and the two bar panels exist to show it:
rice is {int(tot['Rice']['runs']):,} samples at {tot['Rice']['localities']} localities because the rice data are large
GWAS panels grown at one farm, while wheat is {int(tot['Wheat']['runs']):,} at {tot['Wheat']['localities']} because the
wheat data are rust surveys that sample broadly. (a) alone reads as a wheat map
and (b) alone reads as a rice cohort; both are true.


WHAT IS NOT SHOWN

{n_unplaced} of the {n_total:,} samples carry no location at all and are absent from the map
while remaining in (b), (c) and (d).

The {n_ctr} samples drawn at country centroids are not a geocoding failure. Most are
rust surveys where the submitter recorded the country an isolate came from and
no collection site, and ENA holds no latitude, longitude or locality field for
them. Where a finer value exists it has been pursued: supplementary tables were
imported for the Ada21 projects and PRJEB36485, Lewis et al. 2024 Dataset S2
moved 45 of PRJEB65589's samples from a country to a named site, and
seeds/missing_localities.tsv is the worklist of localities that do not place,
and carries {applied} reviewed corrections for names the gazetteer could not match
as written. The rows still without a correction are open work.

Three crops below a 100-sample floor are excluded from every panel: {dropped}.
Barley's absence is a property of the archive, not of this figure - there is no
field barley study in the cohort, only incidental barley samples inside wheat
rust surveys. Note that the kraken read-based host call reports far more barley
than this; it is wrong, and systematically so, in exactly these rust surveys.
See seeds/found.tsv, 2026-10-09.

Localities are placed at four precisions, recorded per locality in
data/gold/cereal_localities.tsv: {pr['locality']:,} samples at a name that resolved as given,
{pr['locality-nofacility']:,} after a research-facility name was dropped (for example "USA: Nebraska,
Lincoln (UNL Havelock Research Farm)" placed as Lincoln, Nebraska), {corrected}
through a reviewed spelling correction, and {pr['region']} at province level.

A caution that belongs with any use of these panels: crop is almost perfectly
confounded with sampling design. Wheat is 96% disease-selected while rice and
sorghum are 100% unselected, so differences between crops in this cohort cannot
be separated from differences between study types. Run cohort.py for the
cross-tab.


SHORT CAPTION

Distribution of {n_total:,} field cereal RNA-seq samples from {projects} BioProjects, coloured
by crop. (a) One point per locality and crop, point area proportional to log
sample count. Circles are {n_geo:,} samples at {len({r['location'] for r in geo})} geocoded localities;
diamonds are {n_ctr} samples that name only a country, drawn at its centroid and
not at a collection site; {n_unplaced} samples carry no location and are absent.
(b, c) The same cohort as samples, and as distinct localities finer than a
country. (d) Samples per year of collection, stacked by crop, for the {n_dated:,}
samples carrying a date.


SOURCES

  figure   01a_Literature/report/figures/map_crop_origins.R  (writes panels/)
  caption  01a_Literature/report/figures/caption.py
  data     01a_Literature/data/gold/crop_map.tsv, crop_totals.tsv, crop_year.tsv
  prep     01a_Literature/report/figures/prep_crop_map.py
  hosts    01a_Literature/report/host_summary.py --per-run
  geocode  01a_Literature/retrieve/geocode_localities.py
  missing  01a_Literature/seeds/missing_localities.tsv
"""
    OUT.write_text(txt)
    print(f"wrote {OUT}")
    print(f"  {n_total:,} samples, {projects} projects, {n_geo:,} geocoded, "
          f"{n_ctr} at centroids, {n_unplaced} absent, {applied} spelling corrections")


if __name__ == "__main__":
    main()
